apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    app: mysql-exporter
  name: mysql-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-exporter
      name: mysql-exporter
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_NAME
          value: admin:beta123!@(beta-mysql.cqiifus5uiok.us-east-1.rds.amazonaws.com:3306)/beta_prod
        image: prom/mysqld-exporter:master
        imagePullPolicy: IfNotPresent
        name: mysql-exporter-container-0
        ports:
        - containerPort: 9104
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
     

