apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mysql-exporter-service
  namespace: default
spec:
  hosts:
  - "mysql.com"
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /metrics
    route:
    - destination:
        port:
          number: 9104
        host: mysql-exporter-service
