apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: default
  labels:
    app: mysql-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9104
    name: mysql-exporter
    protocol: TCP
    targetPort: 9104
  selector:
    app: mysql-exporter
