apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-server
  namespace: default
  
spec:
  gateways:
  - httpbin-gateway
  hosts:
  - prometheus.com
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-server
        port:
          number: 80