apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: default
  labels:
    app: blackbox-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9115
    name: blackbox-exporter
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox-exporter
