apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: prometheus-broker-exporter
    meta.helm.sh/release-namespace: default
  labels:
    app: prometheus-rabbitmq-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-rabbitmq-exporter-1.3.0
    heritage: Helm
    release: prometheus-broker-exporter
  name: prometheus-broker-exporter-prometheus-rabbitmq-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-rabbitmq-exporter
      release: prometheus-broker-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-rabbitmq-exporter
        release: prometheus-broker-exporter
    spec:
      containers:
      - env:
        - name: RABBIT_URL
          value: https://172.20.4.56:15672
        - name: RABBIT_USER
          value: admin
        - name: RABBIT_PASSWORD
          value: alpha123!
        - name: PUBLISH_PORT
          value: "9419"
        - name: LOG_LEVEL
          value: info
        - name: RABBIT_CAPABILITIES
          value: bert,no_sort
        - name: INCLUDE_QUEUES
          value: .*
        - name: INCLUDE_VHOST
          value: .*
        - name: SKIP_QUEUES
          value: ^$
        - name: SKIPVERIFY
          value: "false"
        - name: SKIP_VHOST
          value: ^$
        - name: RABBIT_EXPORTERS
          value: exchange,node,overview,queue
        - name: OUTPUT_FORMAT
          value: TTY
        - name: RABBIT_TIMEOUT
          value: "30"
        - name: MAX_QUEUES
          value: "0"
        image: kbudde/rabbitmq-exporter:v0.29.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: publish
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus-rabbitmq-exporter
        ports:
        - containerPort: 9419
          name: publish
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: publish
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "0"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10002
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-broker-exporter-prometheus-rabbitmq-exporter
      serviceAccountName: prometheus-broker-exporter-prometheus-rabbitmq-exporter
      terminationGracePeriodSeconds: 30
